packloadall
syntax enable
set noerrorbells
set incsearch
set nu
set nowrap
set noswapfile
set nobackup
set undodir="/.vim/undodir
set undofile
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set noshiftround

"colorscheme monokai

let g:ctrlp_custom_ignore = { 
  \ 'dir':  '\v[\/](\.git|autogenerated|card|bazel-out|build|BUILD|map_time_machine|third-party)',
  \ 'file': '\v\.(exe|so|dll|pyc|bag)$',
  \}
let g:ctrlp_max_files = 200000
let g:ctrlp_max_depth = 100
let g:ctrlp_map = '<c-p>'
